name: omspos
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  eva_icons_flutter: ^3.1.0
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  fluttertoast: ^8.2.8
  page_transition: ^2.1.0

  # Date/Time
  nepali_date_picker: ^7.0.0
  nepali_utils: ^3.0.3
  intl: ^0.20.2

  # Networking
  dio: ^5.8.0+1
  http: ^1.4.0
  connectivity_plus: ^6.1.4

  # State Management & Storage
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  sqflite: ^2.4.2

  # File/PDF Handling
  pdf: ^3.11.1
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  path: ^1.8.2

  # Device & Package Info
  device_info_plus: ^11.1.1
  package_info_plus: ^8.3.0

  # Printing
  sunmi_printer_plus: ^4.1.0

  # Images
  cached_network_image: ^3.4.1
  font_awesome_icon_class: ^0.0.6
  flutter_map: ^8.1.1
  go_router: ^16.0.0
  flutter_cache_manager: ^3.4.1
  supabase_flutter: ^2.9.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  onesignal_flutter: ^5.3.4
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  google_sign_in: ^7.2.0

  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/locales/
    - assets/lottie/
